### PR TITLE
Added Gemfile

### PR DESCRIPTION
**Pull request by lukaszklis**

### CODE REVIEW

**Comment by verpixelt** [comment]
I'm not that familiar with Ruby. What exactly happens here? Why do we need this?

**Comment by lukaszklis** [comment]
Gemfile contains the list of the gem dependencies that you need to have installed in order to run this site locally (according to the current README by running `jekyll serve --watch`). It may happen that you don't have jekyll or compass installed locally. ;)

**Comment by verpixelt** [comment]
Thanks for the contribution and also the explanation ;)

**Comment by lukaszklis** [comment]
You're welcome! Happy to help! \o/

**Pull request merged**
